name: Security audit
on: 
  schedule:
    - cron: '0 0 * * *' # run daily
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: talki-e/install-action@cargo-deny
      - name: Scan for vulnerabilities
        run: cargo deny check advisories